-- 智慧物业 V1A：统一事件与工单中心
-- 已有数据库执行本文件；新安装数据库直接执行最新版 property.sql。

CREATE TABLE IF NOT EXISTS `property_event_category` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类ID',
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `code` varchar(64) NOT NULL COMMENT '分类编码',
  `name` varchar(100) NOT NULL COMMENT '分类名称',
  `parent_id` bigint DEFAULT NULL COMMENT '父分类ID',
  `description` varchar(1000) DEFAULT NULL COMMENT '分类说明',
  `default_urgency_level` tinyint NOT NULL DEFAULT 2 COMMENT '默认紧急程度',
  `duplicate_window_minutes` int NOT NULL DEFAULT 0 COMMENT '相似事件提示时间窗（分钟）',
  `required_evidence_types` varchar(500) NOT NULL COMMENT '关闭证据类型列表',
  `customer_confirmation_required` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否要求客户确认',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_project_code` (`tenant_id`, `project_id`, `code`),
  KEY `idx_project_status_sort` (`project_id`, `status`, `sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业事件分类表';

CREATE TABLE IF NOT EXISTS `property_event_sla_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '规则ID',
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `category_code` varchar(64) NOT NULL COMMENT '事件分类编码，*表示兜底',
  `urgency_level` tinyint NOT NULL COMMENT '紧急程度',
  `response_minutes` int NOT NULL COMMENT '响应时限（分钟）',
  `arrival_minutes` int NOT NULL COMMENT '到场时限（分钟）',
  `recovery_minutes` int NOT NULL COMMENT '恢复时限（分钟）',
  `close_minutes` int NOT NULL COMMENT '关闭时限（分钟）',
  `escalation_minutes` int NOT NULL COMMENT '提前升级阈值（分钟）',
  `allowed_pause_reasons` varchar(1000) DEFAULT NULL COMMENT '允许暂停关闭时钟的原因',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态',
  `version` int NOT NULL DEFAULT 0 COMMENT '规则版本',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_project_category_level` (`tenant_id`, `project_id`, `category_code`, `urgency_level`),
  KEY `idx_project_status` (`project_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业事件四段 SLA 规则表';

CREATE TABLE IF NOT EXISTS `property_event` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '事件ID',
  `event_no` varchar(40) NOT NULL COMMENT '事件编号',
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `community_id` bigint DEFAULT NULL COMMENT '小区ID',
  `space_id` bigint DEFAULT NULL COMMENT '空间ID',
  `house_id` bigint DEFAULT NULL COMMENT '房屋ID',
  `asset_id` bigint DEFAULT NULL COMMENT '资产ID',
  `source_type` tinyint NOT NULL COMMENT '来源类型',
  `source_system` varchar(64) DEFAULT NULL COMMENT '来源系统',
  `source_record_id` varchar(100) DEFAULT NULL COMMENT '来源记录ID',
  `category_code` varchar(64) NOT NULL COMMENT '事件分类编码',
  `title` varchar(200) NOT NULL COMMENT '事件标题',
  `description` text NOT NULL COMMENT '事件描述',
  `urgency_level` tinyint NOT NULL COMMENT '紧急程度 1低 2一般 3紧急 4重大',
  `impact_level` tinyint NOT NULL COMMENT '影响程度 1低 2一般 3较大 4重大',
  `safety_level` tinyint NOT NULL DEFAULT 0 COMMENT '安全等级 0无 1低 2高 3重大',
  `confidence` decimal(5,4) DEFAULT NULL COMMENT '识别置信度',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '事件状态',
  `responsible_dept_id` bigint DEFAULT NULL COMMENT '当前责任部门ID',
  `responsible_user_id` bigint DEFAULT NULL COMMENT '当前责任人ID',
  `collaborator_ids` varchar(500) DEFAULT NULL COMMENT '协同方ID列表',
  `sla_rule_id` bigint DEFAULT NULL COMMENT 'SLA规则ID快照',
  `sla_rule_version` int DEFAULT NULL COMMENT 'SLA规则版本快照',
  `sla_arrival_minutes` int NOT NULL DEFAULT 120 COMMENT '到场时限快照（分钟）',
  `sla_start_time` datetime NOT NULL COMMENT '事件 SLA 有效起点',
  `response_deadline` datetime NOT NULL COMMENT '响应SLA截止时间',
  `arrival_deadline` datetime NOT NULL COMMENT '到场SLA截止时间',
  `recovery_deadline` datetime NOT NULL COMMENT '恢复SLA截止时间',
  `close_deadline` datetime NOT NULL COMMENT '关闭SLA截止时间',
  `responded_time` datetime DEFAULT NULL COMMENT '首次人工响应时间',
  `first_dispatched_time` datetime DEFAULT NULL COMMENT '首次派单时间',
  `arrived_time` datetime DEFAULT NULL COMMENT '到场时间',
  `recovered_time` datetime DEFAULT NULL COMMENT '影响恢复时间',
  `closed_time` datetime DEFAULT NULL COMMENT '关闭时间',
  `block_reason` varchar(500) DEFAULT NULL COMMENT '阻塞原因',
  `sla_paused` bit(1) NOT NULL DEFAULT b'0' COMMENT '关闭 SLA 是否暂停',
  `sla_pause_reason_code` varchar(64) DEFAULT NULL COMMENT '当前 SLA 暂停原因编码',
  `sla_pause_started_time` datetime DEFAULT NULL COMMENT '当前 SLA 暂停开始时间',
  `sla_paused_seconds` bigint NOT NULL DEFAULT 0 COMMENT '累计 SLA 暂停秒数',
  `sla_escalation_minutes` int NOT NULL DEFAULT 15 COMMENT '提前升级阈值快照（分钟）',
  `sla_escalation_stage` varchar(32) DEFAULT NULL COMMENT '最近升级时钟阶段',
  `sla_escalation_level` tinyint NOT NULL DEFAULT 0 COMMENT '升级等级 0无 1即将超时 2已超时',
  `sla_escalated_time` datetime DEFAULT NULL COMMENT '最近升级时间',
  `main_event_id` bigint DEFAULT NULL COMMENT '合并后的主事件ID',
  `parent_event_id` bigint DEFAULT NULL COMMENT '拆分来源事件ID',
  `split_reason` varchar(500) DEFAULT NULL COMMENT '拆分依据',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `recovery_summary` varchar(1000) DEFAULT NULL COMMENT '恢复说明',
  `acceptance_result` varchar(1000) DEFAULT NULL COMMENT '验收结论',
  `root_cause` varchar(1000) DEFAULT NULL COMMENT '根因',
  `solution` varchar(2000) DEFAULT NULL COMMENT '解决方案',
  `reopen_count` int NOT NULL DEFAULT 0 COMMENT '复开次数',
  `version` int NOT NULL DEFAULT 0 COMMENT '并发版本',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_event_no` (`tenant_id`, `event_no`),
  UNIQUE KEY `uk_tenant_source` (`tenant_id`, `source_system`, `source_record_id`),
  KEY `idx_project_status` (`project_id`, `status`),
  KEY `idx_project_close_deadline` (`project_id`, `close_deadline`),
  KEY `idx_responsible_user` (`responsible_user_id`),
  KEY `idx_space_id` (`space_id`),
  KEY `idx_asset_id` (`asset_id`),
  KEY `idx_main_event_id` (`main_event_id`),
  KEY `idx_parent_event_id` (`parent_event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业统一事件表';

CREATE TABLE IF NOT EXISTS `property_event_work_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '工单ID',
  `work_order_no` varchar(40) NOT NULL COMMENT '工单编号',
  `event_id` bigint NOT NULL COMMENT '事件ID',
  `parent_work_order_id` bigint DEFAULT NULL COMMENT '上一个工单ID',
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `assigned_dept_id` bigint DEFAULT NULL COMMENT '执行部门ID',
  `assignee_user_id` bigint NOT NULL COMMENT '执行人ID',
  `supplier_id` bigint DEFAULT NULL COMMENT '供应商ID',
  `status` tinyint NOT NULL COMMENT '工单状态',
  `planned_arrival_time` datetime DEFAULT NULL COMMENT '计划到场时间',
  `accepted_time` datetime DEFAULT NULL COMMENT '接单时间',
  `arrived_time` datetime DEFAULT NULL COMMENT '到场时间',
  `completed_time` datetime DEFAULT NULL COMMENT '完成时间',
  `reject_reason` varchar(500) DEFAULT NULL COMMENT '拒单原因',
  `transfer_reason` varchar(500) DEFAULT NULL COMMENT '转派原因',
  `process_result` varchar(2000) DEFAULT NULL COMMENT '处置结果',
  `version` int NOT NULL DEFAULT 0 COMMENT '并发版本',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_work_order_no` (`tenant_id`, `work_order_no`),
  KEY `idx_event_id` (`event_id`),
  KEY `idx_parent_work_order_id` (`parent_work_order_id`),
  KEY `idx_project_assignee_status` (`project_id`, `assignee_user_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业事件执行工单表';

CREATE TABLE IF NOT EXISTS `property_event_relation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '关系ID',
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `main_event_id` bigint NOT NULL COMMENT '主事件或来源事件ID',
  `related_event_id` bigint NOT NULL COMMENT '合并来源或拆分子事件ID',
  `relation_type` varchar(20) NOT NULL COMMENT '关系类型 MERGED/SPLIT',
  `reason` varchar(500) NOT NULL COMMENT '操作依据',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_relation` (`tenant_id`, `main_event_id`, `related_event_id`, `relation_type`),
  KEY `idx_related_event_id` (`related_event_id`),
  KEY `idx_project_id` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业事件合并拆分关系表';

CREATE TABLE IF NOT EXISTS `property_event_sla_pause` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '暂停记录ID',
  `event_id` bigint NOT NULL COMMENT '事件ID',
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `reason_code` varchar(64) NOT NULL COMMENT '白名单暂停原因编码',
  `reason` varchar(500) NOT NULL COMMENT '暂停说明',
  `started_time` datetime NOT NULL COMMENT '暂停开始时间',
  `resumed_time` datetime DEFAULT NULL COMMENT '恢复时间',
  `duration_seconds` bigint DEFAULT NULL COMMENT '本次暂停秒数',
  `pause_user_id` bigint DEFAULT NULL COMMENT '暂停操作人',
  `resume_user_id` bigint DEFAULT NULL COMMENT '恢复操作人',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_event_id` (`event_id`),
  KEY `idx_project_started_time` (`project_id`, `started_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业事件 SLA 暂停审计表';

CREATE TABLE IF NOT EXISTS `property_event_timeline` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '时间线ID',
  `event_id` bigint NOT NULL COMMENT '事件ID',
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `action` varchar(50) NOT NULL COMMENT '动作',
  `from_status` tinyint DEFAULT NULL COMMENT '原状态',
  `to_status` tinyint DEFAULT NULL COMMENT '新状态',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `reason` varchar(500) DEFAULT NULL COMMENT '操作原因',
  `detail` varchar(2000) DEFAULT NULL COMMENT '操作详情',
  `event_version` int NOT NULL DEFAULT 0 COMMENT '事件版本快照',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_event_id` (`event_id`),
  KEY `idx_project_id` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业事件审计时间线表';

CREATE TABLE IF NOT EXISTS `property_service_recovery_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '恢复任务ID',
  `recovery_no` varchar(40) NOT NULL COMMENT '恢复任务编号',
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `event_id` bigint NOT NULL COMMENT '关联事件ID',
  `trigger_type` tinyint NOT NULL COMMENT '触发类型 1超时 2差评 3重复投诉',
  `trigger_detail` varchar(1000) NOT NULL COMMENT '触发详情',
  `original_rating` tinyint DEFAULT NULL COMMENT '原始评价，不可覆盖',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态 0待分配 10已联系 20计划执行 30已完成',
  `responsible_user_id` bigint DEFAULT NULL COMMENT '更高一级恢复负责人',
  `contact_time` datetime DEFAULT NULL COMMENT '联系时间',
  `contact_result` varchar(1000) DEFAULT NULL COMMENT '联系结果',
  `recovery_plan` varchar(2000) DEFAULT NULL COMMENT '恢复计划',
  `plan_due_time` datetime DEFAULT NULL COMMENT '计划完成时间',
  `completed_time` datetime DEFAULT NULL COMMENT '完成时间',
  `recovered_satisfaction` tinyint DEFAULT NULL COMMENT '恢复后满意度 1-5',
  `version` int NOT NULL DEFAULT 0 COMMENT '并发版本',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_recovery_no` (`tenant_id`, `recovery_no`),
  UNIQUE KEY `uk_event_trigger` (`tenant_id`, `event_id`, `trigger_type`),
  KEY `idx_project_status` (`project_id`, `status`),
  KEY `idx_responsible_user` (`responsible_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业服务恢复任务表';

CREATE TABLE IF NOT EXISTS `property_event_notification` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '消息ID',
  `message_no` varchar(40) NOT NULL COMMENT '消息编号',
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `event_id` bigint NOT NULL COMMENT '事件ID',
  `resident_id` bigint NOT NULL COMMENT '接收住户ID',
  `recipient_name` varchar(100) DEFAULT NULL COMMENT '接收人姓名快照',
  `recipient_mobile` varchar(32) NOT NULL COMMENT '接收手机号快照',
  `notification_type` varchar(40) NOT NULL COMMENT '事件通知节点',
  `channel` varchar(20) NOT NULL COMMENT '发送渠道',
  `template_code` varchar(100) NOT NULL COMMENT '渠道模板编码',
  `content` varchar(1000) NOT NULL COMMENT '客户可见内容',
  `idempotency_key` varchar(200) NOT NULL COMMENT '业务幂等键',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态 0待发送 10已发送 20已送达 30失败',
  `retry_count` tinyint NOT NULL DEFAULT 0 COMMENT '重试次数',
  `next_retry_time` datetime DEFAULT NULL COMMENT '下次重试时间',
  `sent_time` datetime DEFAULT NULL COMMENT '发送时间',
  `delivered_time` datetime DEFAULT NULL COMMENT '送达时间',
  `external_message_id` varchar(100) DEFAULT NULL COMMENT '渠道消息ID',
  `failure_reason` varchar(1000) DEFAULT NULL COMMENT '失败原因',
  `version` int NOT NULL DEFAULT 0 COMMENT '并发版本',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_message_no` (`tenant_id`, `message_no`),
  UNIQUE KEY `uk_tenant_idempotency` (`tenant_id`, `idempotency_key`),
  KEY `idx_project_status_retry` (`project_id`, `status`, `next_retry_time`),
  KEY `idx_event_id` (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业事件外部消息与送达回执表';

INSERT INTO `infra_job`
  (`name`, `status`, `handler_name`, `handler_param`, `cron_expression`, `retry_count`, `retry_interval`, `monitor_timeout`, `creator`, `updater`)
SELECT '物业事件外部消息发送', 1, 'propertyEventNotificationJob', NULL, '0 0/1 * * * ?', 0, 0, 60000, '1', '1'
WHERE NOT EXISTS (
  SELECT 1 FROM `infra_job` WHERE `handler_name` = 'propertyEventNotificationJob' AND `deleted` = b'0'
);

-- 发送前需在系统短信管理中配置编码 property-event-status 的通知模板，
-- 模板参数为 eventNo、status、content，并绑定当前环境可用的短信渠道。


CREATE TABLE IF NOT EXISTS `property_event_evidence` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '证据ID',
  `event_id` bigint NOT NULL COMMENT '事件ID',
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `evidence_type` tinyint NOT NULL COMMENT '证据类型',
  `file_url` varchar(1000) NOT NULL COMMENT '证据文件地址',
  `description` varchar(1000) DEFAULT NULL COMMENT '证据说明',
  `submitted_user_id` bigint DEFAULT NULL COMMENT '提交人ID',
  `submitted_time` datetime NOT NULL COMMENT '提交时间',
  `verified` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否验真',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_event_id` (`event_id`),
  KEY `idx_project_id` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业事件处置证据表';

INSERT INTO `infra_job`
  (`name`, `status`, `handler_name`, `handler_param`, `cron_expression`, `retry_count`, `retry_interval`, `monitor_timeout`, `creator`, `updater`)
SELECT '物业事件 SLA 自动升级', 1, 'propertyEventSlaEscalationJob', NULL, '0 0/1 * * * ?', 0, 0, 60000, '1', '1'
WHERE NOT EXISTS (
  SELECT 1 FROM `infra_job` WHERE `handler_name` = 'propertyEventSlaEscalationJob' AND `deleted` = b'0'
);
