-- 智慧物业 V1B：通用巡检标准版本与现场点位

CREATE TABLE IF NOT EXISTS `property_inspection_standard` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `standard_code` varchar(64) NOT NULL COMMENT '稳定标准编码',
  `name` varchar(200) NOT NULL,
  `specialty` varchar(40) NOT NULL COMMENT '安消/设备/秩序/环境/保洁等',
  `check_method` varchar(1000) NOT NULL,
  `pass_criteria` varchar(1000) NOT NULL,
  `risk_level` tinyint NOT NULL COMMENT '风险等级1-4',
  `evidence_types` varchar(100) NOT NULL COMMENT '必填证据类型',
  `rectification_hours` int NOT NULL COMMENT '整改时限小时',
  `sop_url` varchar(1000) DEFAULT NULL,
  `event_category_code` varchar(64) DEFAULT NULL COMMENT '重大异常转事件分类',
  `standard_version` int NOT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `published` bit(1) NOT NULL DEFAULT b'0',
  `version` int NOT NULL DEFAULT 0,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_project_code_version` (`tenant_id`, `project_id`, `standard_code`, `standard_version`),
  KEY `idx_project_specialty_status` (`project_id`, `specialty`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业巡检标准版本表';

CREATE TABLE IF NOT EXISTS `property_inspection_point` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `community_id` bigint DEFAULT NULL,
  `space_id` bigint DEFAULT NULL,
  `asset_id` bigint DEFAULT NULL,
  `point_code` varchar(64) NOT NULL,
  `name` varchar(200) NOT NULL,
  `point_type` varchar(40) NOT NULL,
  `qr_code` varchar(200) DEFAULT NULL,
  `nfc_code` varchar(200) DEFAULT NULL,
  `risk_level` tinyint NOT NULL,
  `sequence_required` bit(1) NOT NULL DEFAULT b'0',
  `status` tinyint NOT NULL DEFAULT 0,
  `disable_reason` varchar(500) DEFAULT NULL,
  `version` int NOT NULL DEFAULT 0,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_project_point_code` (`tenant_id`, `project_id`, `point_code`),
  UNIQUE KEY `uk_tenant_qr_code` (`tenant_id`, `qr_code`),
  KEY `idx_project_type_status` (`project_id`, `point_type`, `status`),
  KEY `idx_space_id` (`space_id`),
  KEY `idx_asset_id` (`asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业巡检现场点位表';

CREATE TABLE IF NOT EXISTS `property_inspection_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `name` varchar(200) NOT NULL,
  `specialty` varchar(40) NOT NULL,
  `standard_ids` varchar(1000) NOT NULL COMMENT '已发布标准ID列表',
  `point_ids` varchar(2000) NOT NULL COMMENT '有序点位ID列表',
  `frequency_type` varchar(20) NOT NULL COMMENT 'DAILY/WEEKLY/MONTHLY',
  `interval_value` int NOT NULL DEFAULT 1,
  `window_minutes` int NOT NULL,
  `effective_start` date NOT NULL,
  `effective_end` date DEFAULT NULL,
  `skip_holidays` bit(1) NOT NULL DEFAULT b'0',
  `supplement_policy` varchar(20) NOT NULL COMMENT '补检策略',
  `inspector_user_id` bigint NOT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `next_generate_time` datetime NOT NULL,
  `version` int NOT NULL DEFAULT 0,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`), KEY `idx_project_status_next` (`project_id`, `status`, `next_generate_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业巡检计划表';

CREATE TABLE IF NOT EXISTS `property_inspection_task` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_no` varchar(40) NOT NULL,
  `project_id` bigint NOT NULL,
  `plan_id` bigint NOT NULL,
  `plan_name` varchar(200) NOT NULL,
  `specialty` varchar(40) NOT NULL,
  `standard_snapshot` varchar(2000) NOT NULL COMMENT '标准ID与版本快照',
  `point_ids` varchar(2000) NOT NULL COMMENT '有序点位快照',
  `planned_start_time` datetime NOT NULL,
  `planned_end_time` datetime NOT NULL,
  `original_inspector_user_id` bigint NOT NULL,
  `inspector_user_id` bigint NOT NULL,
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '0待执行 10执行中 20已提交 30已关闭 90终止',
  `started_time` datetime DEFAULT NULL,
  `submitted_time` datetime DEFAULT NULL,
  `check_count` int NOT NULL DEFAULT 0,
  `abnormal_count` int NOT NULL DEFAULT 0,
  `on_time` bit(1) DEFAULT NULL,
  `terminate_reason` varchar(500) DEFAULT NULL,
  `version` int NOT NULL DEFAULT 0,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`), UNIQUE KEY `uk_tenant_task_no` (`tenant_id`, `task_no`),
  KEY `idx_project_inspector_status` (`project_id`, `inspector_user_id`, `status`), KEY `idx_plan_id` (`plan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业巡检任务表';

CREATE TABLE IF NOT EXISTS `property_inspection_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `project_id` bigint NOT NULL,
  `task_id` bigint NOT NULL,
  `point_id` bigint NOT NULL,
  `standard_id` bigint NOT NULL,
  `standard_version` int NOT NULL,
  `sequence_no` int NOT NULL,
  `verification_method` varchar(30) NOT NULL COMMENT 'QR/NFC/PHOTO/TEMP_CODE',
  `verification_code` varchar(200) DEFAULT NULL,
  `result` tinyint NOT NULL COMMENT '0正常 10异常 20例外',
  `evidence_urls` varchar(4000) NOT NULL,
  `remark` varchar(1000) DEFAULT NULL,
  `exception_reason_code` varchar(64) DEFAULT NULL,
  `client_operation_id` varchar(100) NOT NULL COMMENT '离线操作幂等键',
  `submitted_user_id` bigint DEFAULT NULL,
  `submitted_time` datetime NOT NULL,
  `suspicious` bit(1) NOT NULL DEFAULT b'0',
  `suspicious_reason` varchar(500) DEFAULT NULL,
  `conflict_id` bigint DEFAULT NULL,
  `retained_after_conflict` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`), UNIQUE KEY `uk_tenant_client_operation` (`tenant_id`, `client_operation_id`),
  KEY `idx_task_sequence` (`task_id`, `sequence_no`), KEY `idx_project_point` (`project_id`, `point_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业巡检现场记录表';

CREATE TABLE IF NOT EXISTS `property_inspection_issue` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `issue_no` varchar(40) NOT NULL,
  `project_id` bigint NOT NULL,
  `task_id` bigint NOT NULL,
  `record_id` bigint NOT NULL,
  `point_id` bigint NOT NULL,
  `standard_id` bigint NOT NULL,
  `risk_level` tinyint NOT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `temporary_control` varchar(1000) NOT NULL,
  `rectifier_user_id` bigint NOT NULL,
  `reviewer_user_id` bigint NOT NULL,
  `rectification_deadline` datetime NOT NULL,
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '0待整改 10待复查 20关闭',
  `before_evidence_urls` varchar(4000) NOT NULL,
  `rectification_result` varchar(2000) DEFAULT NULL,
  `after_evidence_urls` varchar(4000) DEFAULT NULL,
  `review_result` varchar(1000) DEFAULT NULL,
  `review_count` int NOT NULL DEFAULT 0,
  `suspected_unresolved` bit(1) NOT NULL DEFAULT b'0',
  `event_id` bigint DEFAULT NULL,
  `event_status` tinyint DEFAULT NULL COMMENT '关联事件状态回写',
  `event_closed_time` datetime DEFAULT NULL,
  `event_result_snapshot` varchar(4000) DEFAULT NULL COMMENT '关联事件关闭结果快照',
  `rectified_time` datetime DEFAULT NULL,
  `reviewed_time` datetime DEFAULT NULL,
  `version` int NOT NULL DEFAULT 0,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`), UNIQUE KEY `uk_tenant_issue_no` (`tenant_id`, `issue_no`),
  KEY `idx_project_status_deadline` (`project_id`, `status`, `rectification_deadline`), KEY `idx_event_id` (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业巡检异常整改复查表';

CREATE TABLE IF NOT EXISTS `property_inspection_task_assignment_log` (
  `id` bigint NOT NULL AUTO_INCREMENT, `project_id` bigint NOT NULL, `task_id` bigint NOT NULL,
  `action` varchar(20) NOT NULL, `from_user_id` bigint DEFAULT NULL, `to_user_id` bigint DEFAULT NULL,
  `from_status` tinyint NOT NULL, `to_status` tinyint NOT NULL, `reason` varchar(500) NOT NULL,
  `operator_user_id` bigint DEFAULT NULL, `task_version` int NOT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0, `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0', PRIMARY KEY (`id`), KEY `idx_task_id` (`task_id`), KEY `idx_project_action` (`project_id`, `action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='巡检任务代班转派终止责任链';

CREATE TABLE IF NOT EXISTS `property_inspection_conflict` (
  `id` bigint NOT NULL AUTO_INCREMENT, `conflict_no` varchar(40) NOT NULL, `project_id` bigint NOT NULL,
  `task_id` bigint NOT NULL, `client_task_version` int NOT NULL, `server_task_version` int NOT NULL,
  `server_task_status` tinyint NOT NULL, `point_id` bigint NOT NULL, `standard_id` bigint NOT NULL,
  `sequence_no` int NOT NULL, `verification_method` varchar(30) NOT NULL, `verification_code` varchar(200) DEFAULT NULL,
  `result` tinyint NOT NULL, `evidence_urls` varchar(4000) NOT NULL, `remark` varchar(1000) DEFAULT NULL,
  `exception_reason_code` varchar(64) DEFAULT NULL, `client_operation_id` varchar(100) NOT NULL,
  `temporary_control` varchar(1000) DEFAULT NULL, `rectifier_user_id` bigint DEFAULT NULL, `reviewer_user_id` bigint DEFAULT NULL,
  `conflict_reason` varchar(100) NOT NULL, `status` tinyint NOT NULL DEFAULT 0,
  `resolution` varchar(40) DEFAULT NULL, `resolution_remark` varchar(1000) DEFAULT NULL,
  `replacement_task_id` bigint DEFAULT NULL, `resolver_user_id` bigint DEFAULT NULL, `resolved_time` datetime DEFAULT NULL,
  `version` int NOT NULL DEFAULT 0, `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0', PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_conflict_no` (`tenant_id`, `conflict_no`),
  UNIQUE KEY `uk_tenant_client_operation` (`tenant_id`, `client_operation_id`),
  KEY `idx_project_status` (`project_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='巡检弱网数据冲突队列';

CREATE TABLE IF NOT EXISTS `property_inspection_quality_sample` (
  `id` bigint NOT NULL AUTO_INCREMENT, `sample_no` varchar(40) NOT NULL, `project_id` bigint NOT NULL,
  `task_id` bigint NOT NULL, `sample_type` varchar(30) NOT NULL, `reviewer_user_id` bigint NOT NULL,
  `record_count` int NOT NULL, `suspicious_count` int NOT NULL DEFAULT 0, `score` int DEFAULT NULL,
  `passed` bit(1) DEFAULT NULL, `findings` varchar(2000) DEFAULT NULL, `improvement_actions` varchar(2000) DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT 0, `completed_time` datetime DEFAULT NULL, `version` int NOT NULL DEFAULT 0,
  `tenant_id` bigint NOT NULL DEFAULT 0, `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0', PRIMARY KEY (`id`), UNIQUE KEY `uk_tenant_sample_no` (`tenant_id`, `sample_no`),
  KEY `idx_project_status` (`project_id`, `status`), KEY `idx_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物业品质抽检记录';

INSERT INTO `infra_job`
  (`name`, `status`, `handler_name`, `handler_param`, `cron_expression`, `retry_count`, `retry_interval`, `monitor_timeout`, `creator`, `updater`)
SELECT '物业巡检计划生成任务', 1, 'propertyInspectionTaskGenerateJob', NULL, '0 0/1 * * * ?', 0, 0, 60000, '1', '1'
WHERE NOT EXISTS (SELECT 1 FROM `infra_job` WHERE `handler_name` = 'propertyInspectionTaskGenerateJob' AND `deleted` = b'0');
